name: anti brut force tests

on: [push]

env:
  GO111MODULE: "on"

jobs:
  pipleline_by_makefile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ^1.16

      - name: make lint
        run: make lint

      - name: make build
        run: make build

      - name: make test
        run: make test
